on:
  workflow_call:
    inputs:
      build_command:
        type: string
        default: 'build'
      install_command:
        type: string
        default: 'install'
      test_command:
        type: string
        default: 'test'
      run_lint:
        type: boolean
        default: true
      run_test:
        type: boolean
        default: true
      upload_build_artifact:
        type: boolean
        default: true
      build_artifact_name:
        type: string
        default: npm_build_artifact
      build_artifact_path:
        description: 'A file, directory or wildcard pattern that describes what to upload'
        type: string

jobs:
  npm_install_build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js (v${{matrix.node-version}})
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache-dependency-path: 'package-lock.json'
          cache: npm

      - name: Install
        run: npm ${{ inputs.install_command }}

      - name: Build
        run: npm run ${{ inputs.build_command }}

      - name: Format artifact paths for upload
        id: format_paths
        if: inputs.upload_build_artifact && inputs.build_artifact_path != ''
        run: |
          PATHS=$(echo '${{ inputs.build_artifact_path }}' | jq -r '.[]')
          echo "paths=$PATHS" >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        if: inputs.upload_build_artifact && inputs.build_artifact_path != ''
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ steps.format_paths.outputs.paths }}

      - name: Test
        if: inputs.run_test
        run: npm run ${{ inputs.test_command }}

      - name: Lint
        if: inputs.run_lint
        run: npm run lint