# https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/build-and-push-docker-images-to-amazon-ecr-using-github-actions-and-terraform.html
# https://github.com/aws-samples/docker-ecr-actions-workflow/blob/main/.github/workflows/workflow.yaml

# View access keys:
# https://console.aws.amazon.com/iam/home
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      image_tag:
        type: string
        default: "latest"
      docker_build_dir:
        type: string
        default: "."
      path_to_dockerfile:
        type: string
        default: "Dockerfile"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  aws_ecr:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.repository_name }}
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.path_to_dockerfile }}" \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }}" \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$git_hash"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }}"
          echo "IMAGE ${{ inputs.image_tag }} is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "your_image_tag=${{ inputs.image_tag }}"
          echo "git_image_tag=$git_hash"
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }}"
