name: "Dynamic Values"
on:
  push:
    branches: [ "main" ]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      - name: Print some variables
        run: |
          echo "TIMESTAMP:                            ${{ github.event.repository.updated_at}}";
          echo "RUNNER OS:                            ${{runner.os}}"
          echo "REPO_NAME:                            $REPO_NAME";
          echo "GITHUB REPOSITORY:                    ${GITHUB_REPOSITORY}"
          echo "GITHUB REPOSITORY OWNER:              ${GITHUB_REPOSITORY_OWNER}"
          echo "GITHUB REPOSITORY OWNER:              ${{github.repository_owner}}"
          echo "GITHUB RUN ID:                        ${{github.run_id}}"
          echo "GITHUB RUN ATTEMPT:                   ${{github.run_attempt}}"
          echo "GITHUB REF:                           ${{github.ref}}"
          echo "GITHUB EVENT (PULL REQUEST MERGED?):  ${{github.event.pull_request.merged}}"