name: "On Push Pipeline"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm_actions_basic:
    uses: ./.github/workflows/_npm-install-build-lint-test.yml

  npm_actions_no_build_no_lint_no_test:
    uses: ./.github/workflows/_npm-install-build-lint-test.yml
    with:
      install_command: 'ci'
      run_build: false
      run_lint: false
      run_test: false

  npm_actions_build_no_lint_no_test:
    uses: ./.github/workflows/_npm-install-build-lint-test.yml
    with:
      install_command: 'ci'
#      run_build: true
      run_lint: false
      run_test: false

  npm_actions_build_lint_no_test:
    uses: ./.github/workflows/_npm-install-build-lint-test.yml
    with:
      install_command: 'ci'
#      run_build: true
#      run_lint: false
      run_test: false

  npm_actions_build_lint_test:
    uses: ./.github/workflows/_npm-install-build-lint-test.yml
    with:
      install_command: 'ci'
#      run_build: true
#      run_lint: false
#      run_test: false
